import type { ChronologyEvent, Journey } from '@/lib/types'

/**
 * 義経編の旅程。
 *
 * 大事なのは、同じ一本の線のなかで情報のレイヤーが移り変わることです。
 * 前半と後半は同時代史料で追えますが、両端は物語と能が埋めています。
 */
export const JOURNEY_YOSHITSUNE: Journey = {
  slug: 'yoshitsune',
  title: '鞍馬から平泉へ',
  subtitle: 'KURAMA → HIRAIZUMI',
  stops: [
    {
      step: 1,
      placeSlug: 'kurama',
      name: '鞍馬',
      romaji: 'KURAMA',
      lat: 35.118,
      lon: 135.771,
      year: '1170 頃',
      yearNum: 1170,
      headline: '寺に預けられる',
      note: '父を失った子が京の北の山寺に預けられた、と後世の物語は語ります。同時代の記録に、この数年の姿はありません。',
      layer: 'story',
      plays: ['kurama-tengu'],
    },
    {
      step: 2,
      placeSlug: 'gojo',
      name: '五条',
      romaji: 'GOJO',
      lat: 34.997,
      lon: 135.765,
      year: '1174 頃',
      yearNum: 1174,
      headline: '弁慶と出会う',
      note: '橋の上での出会いです。ただし能では、夜ごと人を斬っているのは牛若のほうです。',
      layer: 'story',
      plays: ['hashi-benkei'],
    },
    {
      step: 3,
      placeSlug: 'omi-kagami',
      name: '近江・鏡',
      romaji: 'KAGAMI',
      lat: 35.079,
      lon: 136.062,
      year: '1174 頃',
      yearNum: 1174.5,
      headline: '元服する',
      note: '東山道の宿で自ら髪を結い、名前を改めたと語られます。少年が武者になる境目に置かれた土地です。',
      layer: 'story',
      plays: ['eboshi-ori', 'kumasaka'],
    },
    {
      step: 4,
      placeSlug: 'hiraizumi',
      name: '平泉',
      romaji: 'HIRAIZUMI',
      lat: 39.0,
      lon: 141.113,
      year: '1174 — 1180',
      yearNum: 1176,
      headline: '奥州に身を寄せる',
      note: '挙兵のときに奥州から駆けつけたと記録されているので、それ以前に北にいたこと自体は裏づけられます。',
      layer: 'chronicle',
      plays: [],
    },
    {
      step: 5,
      placeSlug: 'kisegawa',
      name: '黄瀬川',
      romaji: 'KISEGAWA',
      lat: 35.135,
      lon: 138.916,
      year: '1180',
      yearNum: 1180,
      headline: '頼朝の陣に加わる',
      note: '兄の陣へ駆けつけた記事が幕府の記録に残っています。ここから義経は、史料のなかに現れはじめます。',
      layer: 'chronicle',
      plays: [],
    },
    {
      step: 6,
      placeSlug: 'ichinotani',
      name: '一ノ谷',
      romaji: 'ICHINOTANI',
      lat: 34.646,
      lon: 135.107,
      year: '1184',
      yearNum: 1184,
      headline: '平家の陣を破る',
      note: '合戦そのものは同時代の日記にも記されています。山を駆け下りたという描写のほうは、物語の側にあります。',
      layer: 'history',
      plays: [],
    },
    {
      step: 7,
      placeSlug: 'yashima',
      name: '屋島',
      romaji: 'YASHIMA',
      lat: 34.373,
      lon: 134.108,
      year: '1185',
      yearNum: 1185,
      headline: '海を渡って攻める',
      note: '暴風のなかを少数で渡海したと伝わります。能「八島」は、この戦いを義経自身の霊に語らせます。',
      layer: 'history',
      plays: ['yashima'],
    },
    {
      step: 8,
      placeSlug: 'dannoura',
      name: '壇ノ浦',
      romaji: 'DANNOURA',
      lat: 33.96,
      lon: 130.955,
      year: '1185',
      yearNum: 1185.2,
      headline: '平家が滅びる',
      note: '海峡での決着です。この日を境に、義経の敵は海の向こうではなく東にできます。',
      layer: 'history',
      plays: [],
    },
    {
      step: 9,
      placeSlug: 'kyoto',
      name: '京都',
      romaji: 'KYOTO',
      lat: 35.011,
      lon: 135.768,
      year: '1185',
      yearNum: 1185.4,
      headline: '堀川の館が襲われる',
      note: '鎌倉から送られた武士による夜討です。兄弟の対立が、ここで実力行使に変わります。',
      layer: 'chronicle',
      plays: ['shozon'],
    },
    {
      step: 10,
      placeSlug: 'daimotsu',
      name: '大物浦',
      romaji: 'DAIMOTSU',
      lat: 34.718,
      lon: 135.418,
      year: '1185',
      yearNum: 1185.6,
      headline: '船が嵐に押し戻される',
      note: '西国へ渡ろうとした船団が暴風で散りました。能「船弁慶」は、この嵐を平家の怨霊に置き換えます。',
      layer: 'history',
      plays: ['funabenkei'],
    },
    {
      step: 11,
      placeSlug: 'yoshino',
      name: '吉野',
      romaji: 'YOSHINO',
      lat: 34.366,
      lon: 135.858,
      year: '1185 — 1186',
      yearNum: 1186,
      headline: '山に隠れ、静と別れる',
      note: '吉野で静御前が捕らえられたことは記録に残っています。別れの場面のほうは、物語と能が育てました。',
      layer: 'chronicle',
      plays: ['yoshino-shizuka'],
    },
    {
      step: 12,
      placeSlug: 'ataka',
      name: '安宅',
      romaji: 'ATAKA',
      lat: 36.38,
      lon: 136.418,
      year: '年代不詳',
      yearNum: 1187,
      headline: '関を越える',
      note: '安宅の関での出来事は、「安宅」の作者が書いた場面です。物語の側では、舞台は越中の渡し場でした。',
      layer: 'stage',
      plays: ['ataka'],
    },
    {
      step: 13,
      placeSlug: 'shinobu',
      name: '信夫',
      romaji: 'SHINOBU',
      lat: 37.8,
      lon: 140.446,
      year: '年代不詳',
      yearNum: 1187.5,
      headline: '討たれた従者の家に泊まる',
      note: '佐藤兄弟の母が、山伏姿の一行をそれと知らずにもてなします。能「摂待」の場面です。',
      layer: 'story',
      plays: ['settai'],
    },
    {
      step: 14,
      placeSlug: 'hiraizumi',
      name: '平泉',
      romaji: 'HIRAIZUMI',
      lat: 39.0,
      lon: 141.113,
      year: '1187 — 1189',
      yearNum: 1189,
      headline: '衣川で死ぬ',
      note: '二度目の平泉です。庇護者の死から二年後、義経は攻められて自害したと記録されています。',
      layer: 'chronicle',
      plays: ['nishikido'],
    },
  ],
}

/** 地図に点を持たない、背景としての出来事。年表側にだけ並びます。 */
export const CONTEXT_EVENTS: ChronologyEvent[] = [
  {
    yearNum: 1159,
    year: '1159',
    era: '平治元年',
    headline: '平治の乱',
    detail: '源義朝が敗れ、翌年に落命します。義経の生年はこの年とされますが、確実ではありません。',
    layer: 'chronicle',
    source: '平治物語 / 吾妻鏡',
  },
  {
    yearNum: 1180.5,
    year: '1180',
    era: '治承四年',
    headline: '頼朝が挙兵する',
    detail: '以仁王の令旨を受けて東国で兵が挙がり、内乱が全国に広がります。',
    layer: 'history',
    source: '玉葉',
  },
  {
    yearNum: 1185.8,
    year: '1185',
    era: '文治元年',
    headline: '義経追討の宣旨が下る',
    detail: '嵐で船団を失った直後に、追われる立場が公のものになります。',
    layer: 'history',
    source: '玉葉',
  },
  {
    yearNum: 1189.5,
    year: '1189',
    era: '文治五年',
    headline: '奥州藤原氏が滅びる',
    detail: '義経の死から数か月後、鎌倉の軍が平泉に入ります。北の独立した政治圏が消えます。',
    layer: 'chronicle',
    source: '吾妻鏡',
  },
]
