import type { Place } from '@/lib/types'

/**
 * 土地。
 *
 * 古い地名だけを並べると、読者は「それがいまのどこなのか」を自分で調べることになる。
 * modernName（市区町村まで）と access を必須に近い情報として持たせ、
 * 地図・年表・記事のどこに地名が出ても現在地が併記される状態にする。
 *
 * sites / takeaway は「その土地で実際に見られるもの・持ち帰れるもの」。
 * 観光広告にはしないが、行ける場所を挙げないのは不親切なので載せる。
 */
export const PLACES: Place[] = [
  {
    slug: 'kurama',
    name: '鞍馬',
    romaji: 'KURAMA',
    reading: 'くらま',
    prefecture: '京都府',
    modernName: '京都市左京区鞍馬',
    regionModern: '近畿',
    kind: '山',
    enLocation: 'Kurama, Kyoto',
    region: '山城',
    lat: 35.118,
    lon: 135.771,
    summary: '京の北、鴨川の水源にあたる山中の寺域です。牛若丸が預けられたとされる場所です。',
    today: '市街地から北へ約 12 km。本殿までは山道が続きます。',
    access: '叡山電鉄鞍馬線・鞍馬駅から徒歩。出町柳駅から約 30 分です。',
    sites: [
      { name: '鞍馬寺', note: '牛若丸が預けられたと語られる寺です。山門から本殿まで坂が続きます。' },
      {
        name: '木の根道・奥の院',
        note: '本殿からさらに奥です。兵法を学んだ場と伝えられる一帯にあたります。',
      },
    ],
    plays: ['kurama-tengu'],
    people: ['minamoto-yoshitsune'],
  },
  {
    slug: 'gojo',
    name: '五条',
    romaji: 'GOJO',
    reading: 'ごじょう',
    prefecture: '京都府',
    modernName: '京都市下京区（松原通・五条通の一帯）',
    regionModern: '近畿',
    kind: '都市',
    enLocation: 'Gojo, Kyoto',
    region: '山城',
    lat: 34.997,
    lon: 135.765,
    summary:
      '鴨川を渡る橋と、その東西の街路です。中世の五条大路は、いまの五条通ではなく松原通にあたります。',
    today:
      'いま「五条大橋」と呼ばれている橋は五条通にあり、中世の五条橋の位置とは違います。松原橋のほうが、かつての五条橋の位置にあたります。',
    access: '京阪電鉄・清水五条駅、または市営地下鉄・五条駅から徒歩すぐです。',
    sites: [
      {
        name: '松原橋',
        note: '中世の五条大路が鴨川を渡っていた位置です。物語の舞台にもっとも近いのは、この橋になります。',
      },
      {
        name: '五條天神宮（五条天神社）',
        note: '能「橋弁慶」で弁慶が参詣しようとする社です。松原通沿い、下京区西洞院にあります。',
      },
      {
        name: '五条大橋の牛若丸・弁慶像',
        note: 'いまの五条大橋のたもとです。近代に定着した「橋の上の一騎打ち」の図像を、立体にしたものです。',
      },
    ],
    takeaway: [
      {
        name: '五條天神宮の授与品',
        note: '社頭で御朱印や御守を授与しています。宝船の版画など、この社に由来するものもあります。',
      },
      {
        name: '能楽堂の売店',
        note: '京都には金剛能楽堂と京都観世会館があり、公演日には扇や謡本、手ぬぐいなどが並ぶことがあります。',
      },
    ],
    plays: ['hashi-benkei'],
    people: ['minamoto-yoshitsune', 'benkei'],
  },
  {
    slug: 'omi-kagami',
    name: '近江・鏡',
    romaji: 'KAGAMI',
    reading: 'おうみ・かがみ',
    prefecture: '滋賀県',
    modernName: '蒲生郡竜王町鏡',
    regionModern: '近畿',
    kind: '街道・関',
    enLocation: 'Ryuo, Shiga',
    region: '近江',
    lat: 35.079,
    lon: 136.062,
    summary: '東山道の宿です。奥州へ下る途中で元服したと語られる土地です。',
    today: '旧中山道沿いに、宿場の面影が残っています。',
    access: 'JR東海道本線・野洲駅からバス。名神高速の竜王インターが近くにあります。',
    sites: [
      { name: '鏡の宿の街道筋', note: '旧中山道です。宿場だった地割が残っています。' },
      {
        name: '元服の伝承地',
        note: '元服にちなむ碑と池が伝わっています。伝承であることは、現地の案内にも記されています。',
      },
    ],
    plays: ['eboshi-ori', 'kumasaka'],
    people: ['minamoto-yoshitsune'],
  },
  {
    slug: 'kisegawa',
    name: '黄瀬川',
    romaji: 'KISEGAWA',
    reading: 'きせがわ',
    prefecture: '静岡県',
    modernName: '沼津市・駿東郡清水町',
    regionModern: '中部',
    kind: '川',
    enLocation: 'Numazu, Shizuoka',
    region: '駿河',
    lat: 35.135,
    lon: 138.916,
    summary:
      '富士川の合戦の直後、頼朝の陣に義経が加わった地です。兄弟が初めて顔を合わせた場所とされています。',
    today: '沼津市と清水町の境を流れる川です。対面の伝承地に碑が立っています。',
    access: 'JR東海道本線・三島駅または沼津駅からバスです。',
    sites: [{ name: '対面石', note: '兄弟が対面したと伝えられる石です。八幡神社の境内にあります。' }],
    plays: [],
    people: ['minamoto-yoshitsune', 'minamoto-yoritomo'],
  },
  {
    slug: 'ichinotani',
    name: '一ノ谷',
    romaji: 'ICHINOTANI',
    reading: 'いちのたに',
    prefecture: '兵庫県',
    modernName: '神戸市須磨区',
    regionModern: '近畿',
    kind: '海・浦',
    enLocation: 'Suma, Kobe',
    region: '摂津・播磨境',
    lat: 34.646,
    lon: 135.107,
    summary: '六甲の山が海に迫る隘路です。平家の陣が置かれ、背後の斜面から攻められたと語られます。',
    today: '山陽電鉄・須磨浦公園駅の周辺から、地形の急さが見て取れます。',
    access: '山陽電鉄・須磨浦公園駅から徒歩。JR須磨駅からも近い場所です。',
    sites: [
      {
        name: '須磨浦公園',
        note: '山が海に迫る地形をそのまま歩けます。ロープウェイで斜面を見上げることもできます。',
      },
      { name: '敦盛塚', note: '一ノ谷で討たれた平敦盛を供養すると伝えられる石塔です。' },
    ],
    plays: ['atsumori'],
    people: ['minamoto-yoshitsune', 'taira-atsumori'],
  },
  {
    slug: 'yashima',
    name: '屋島',
    romaji: 'YASHIMA',
    reading: 'やしま',
    prefecture: '香川県',
    modernName: '高松市屋島',
    regionModern: '四国',
    kind: '海・浦',
    enLocation: 'Yashima, Takamatsu',
    region: '讃岐',
    lat: 34.373,
    lon: 134.108,
    summary: '瀬戸内に突き出た溶岩台地です。平家の拠点が置かれました。',
    today: '当時は島で、江戸時代の干拓を経て陸続きになりました。',
    access: 'JR高徳線・屋島駅、ことでん志度線・琴電屋島駅からバスまたは徒歩です。',
    sites: [
      {
        name: '屋島山上',
        note: '台地の上から瀬戸内海を一望できます。海戦の位置関係が、地形として分かります。',
      },
      { name: '屋島寺', note: '山上の寺です。周辺に、合戦にちなむ伝承地が点在しています。' },
    ],
    plays: ['yashima'],
    people: ['minamoto-yoshitsune'],
  },
  {
    slug: 'dannoura',
    name: '壇ノ浦',
    romaji: 'DANNOURA',
    reading: 'だんのうら',
    prefecture: '山口県',
    modernName: '下関市壇之浦町',
    regionModern: '中国',
    kind: '海・浦',
    enLocation: 'Shimonoseki, Yamaguchi',
    region: '長門',
    lat: 33.96,
    lon: 130.955,
    summary: '関門海峡のもっとも狭い部分です。潮の流れが速く、日に四度向きを変えます。',
    today: '関門橋の下に古戦場跡があります。対岸の九州までは約 700 m です。',
    access: 'JR山陽本線・下関駅からバス、「みもすそ川」下車です。',
    sites: [
      { name: 'みもすそ川公園', note: '海峡の最狭部です。潮の速さを、その場で見ることができます。' },
      {
        name: '赤間神宮',
        note: '壇ノ浦で入水した幼帝を祀っています。平家一門の墓と伝えられる塚があります。',
      },
    ],
    plays: [],
    people: ['minamoto-yoshitsune', 'taira-tomomori'],
  },
  {
    slug: 'kyoto',
    name: '京都',
    romaji: 'KYOTO',
    reading: 'きょうと',
    prefecture: '京都府',
    modernName: '京都市（堀川通の周辺）',
    regionModern: '近畿',
    kind: '都市',
    enLocation: 'Kyoto',
    region: '山城',
    lat: 35.011,
    lon: 135.768,
    summary: '義経が滞在した堀川の館がありました。鎌倉と京の関係が緊張していく舞台です。',
    today: '館の正確な位置には諸説あります。堀川通の周辺に伝承地が点在しています。',
    access: 'JR京都駅から市バスや地下鉄で市内各所へ行けます。',
    sites: [
      { name: '堀川通周辺', note: '館の伝承地です。いまは市街地で、遺構は残っていません。' },
      { name: '金剛能楽堂・京都観世会館', note: '京都で能を実際に観られる、主な場所です。' },
    ],
    plays: ['shozon'],
    people: ['minamoto-yoshitsune', 'minamoto-yoritomo'],
  },
  {
    slug: 'daimotsu',
    name: '大物浦',
    romaji: 'DAIMOTSU',
    reading: 'だいもつのうら',
    prefecture: '兵庫県',
    modernName: '尼崎市大物町',
    regionModern: '近畿',
    kind: '海・浦',
    enLocation: 'Amagasaki, Hyogo',
    region: '摂津',
    lat: 34.718,
    lon: 135.418,
    summary:
      '淀川の河口に近い港です。西国へ向かう船がここから出ました。義経の船団が暴風で引き返した地でもあります。',
    today:
      '埋め立てが進み、当時の海岸線はいまの市街地より内陸側にありました。港の気配は残っていません。',
    access: '阪神電鉄本線・大物駅から徒歩すぐ。大阪梅田から約 15 分です。',
    sites: [
      {
        name: '大物主神社',
        note: '船出の地と伝えられる一帯です。境内に、義経や静御前にちなむ碑があります。',
      },
      {
        name: '尼崎市立歴史博物館',
        note: '海岸線の変化や中世の港について、地域の側から確かめられます。',
      },
    ],
    takeaway: [
      {
        name: '海岸線の変化が分かる資料',
        note: '博物館で、埋め立て前後の地形図を確認できます。いま立っている場所が海だったことが分かります。',
      },
    ],
    plays: ['funabenkei'],
    people: ['minamoto-yoshitsune', 'shizuka-gozen', 'taira-tomomori'],
  },
  {
    slug: 'yoshino',
    name: '吉野',
    romaji: 'YOSHINO',
    reading: 'よしの',
    prefecture: '奈良県',
    modernName: '吉野郡吉野町',
    regionModern: '近畿',
    kind: '山',
    enLocation: 'Yoshino, Nara',
    region: '大和',
    lat: 34.366,
    lon: 135.858,
    summary: '金峯山の寺域を抱える山地です。都を追われた人が、繰り返し身を隠した場所でもあります。',
    today: '蔵王堂から奥千本へ、尾根沿いに道が続きます。',
    access: '近鉄吉野線・吉野駅からロープウェイまたは徒歩です。',
    sites: [
      {
        name: '金峯山寺 蔵王堂',
        note: '吉野の中心です。山岳信仰の拠点であり、潜伏の舞台でもありました。',
      },
      {
        name: '勝手神社跡・吉水神社',
        note: '静御前が舞ったと伝えられる場所として、複数の伝承地があります。',
      },
    ],
    plays: ['yoshino-shizuka'],
    people: ['minamoto-yoshitsune', 'shizuka-gozen'],
  },
  {
    slug: 'ataka',
    name: '安宅',
    romaji: 'ATAKA',
    reading: 'あたか',
    prefecture: '石川県',
    modernName: '小松市安宅町',
    regionModern: '中部',
    kind: '街道・関',
    enLocation: 'Komatsu, Ishikawa',
    region: '加賀',
    lat: 36.38,
    lon: 136.418,
    summary: '梯川の河口、日本海に面した砂丘の地です。「安宅」の作者は、ここに関所を置きました。',
    today: '安宅住吉神社と砂浜が隣り合っています。日本海側なので、冬は季節風が強い場所です。',
    access: 'JR北陸本線・小松駅からバスまたはタクシーで約 10 分。小松空港からも近い場所です。',
    sites: [
      {
        name: '安宅の関跡',
        note: '関所があったことを示す同時代の記録はありません。作者が書いた場面を、土地の側が受け止めた場所です。',
      },
      {
        name: '勧進帳の像',
        note: '義経・弁慶・富樫の三人です。能ではなく、歌舞伎「勧進帳」の場面構成に近い立て方になっています。',
      },
      {
        name: '安宅住吉神社',
        note: '関を突破した故事にちなんで、難関突破の社として知られています。受験期には参拝者が多くなります。',
      },
      {
        name: '安宅の関 こまつ勧進帳の里',
        note: '隣接する資料施設です。能から歌舞伎への移り変わりを扱う展示があります。',
      },
    ],
    takeaway: [
      {
        name: '難関突破の御守（安宅住吉神社）',
        note: '関を通ったという物語が、そのまま御利益の形になっている珍しい例です。物語が土地に定着した結果を、持ち帰ることができます。',
      },
    ],
    plays: ['ataka'],
    people: ['minamoto-yoshitsune', 'benkei', 'togashi'],
  },
  {
    slug: 'hokurikudo',
    name: '北陸道',
    romaji: 'HOKURIKUDO',
    reading: 'ほくりくどう',
    prefecture: '—',
    modernName: '福井県・石川県・富山県・新潟県の日本海沿い',
    regionModern: '中部',
    kind: '街道・関',
    enLocation: 'Hokuriku coast, central Japan',
    region: '北陸',
    lat: 36.6,
    lon: 137.0,
    summary: '若狭から越前・加賀・越中・越後へ、日本海沿いに延びる古代からの官道です。',
    access: 'いまの北陸本線・北陸新幹線・国道8号が、おおむね同じ回廊を通っています。',
    plays: ['ataka'],
    people: ['minamoto-yoshitsune'],
  },
  {
    slug: 'shinobu',
    name: '信夫',
    romaji: 'SHINOBU',
    reading: 'しのぶ',
    prefecture: '福島県',
    modernName: '福島市（飯坂・信夫地区）',
    regionModern: '東北',
    kind: '都市',
    enLocation: 'Fukushima City',
    region: '陸奥',
    lat: 37.8,
    lon: 140.446,
    summary: '阿武隈川の西岸です。義経に従った佐藤兄弟の本拠とされています。',
    today: '中世の城館跡と、佐藤氏の墓所が伝わっています。',
    access: '福島交通飯坂線・医王寺前駅から徒歩です。',
    sites: [
      {
        name: '医王寺',
        note: '佐藤継信・忠信の墓と伝えられる塚があります。能「摂待」の背景にあたる土地です。',
      },
      { name: '大鳥城跡', note: '佐藤氏の城館跡と伝えられる丘です。' },
    ],
    plays: ['settai'],
    people: ['sato-tadanobu'],
  },
  {
    slug: 'hiraizumi',
    name: '平泉',
    romaji: 'HIRAIZUMI',
    reading: 'ひらいずみ',
    prefecture: '岩手県',
    modernName: '西磐井郡平泉町',
    regionModern: '東北',
    kind: '社寺',
    enLocation: 'Hiraizumi, Iwate',
    region: '陸奥',
    lat: 39.0,
    lon: 141.113,
    summary:
      '北上川の西、奥州藤原氏三代の拠点です。義経が二度身を寄せ、最後に死んだ土地でもあります。',
    today: '中尊寺・毛越寺を含む一帯が、世界遺産に登録されています。',
    access: 'JR東北本線・平泉駅から徒歩またはバス。東北新幹線・一ノ関駅から約 10 分です。',
    sites: [
      { name: '中尊寺', note: '奥州藤原氏の造営です。金色堂に、三代の遺体が納められています。' },
      {
        name: '高館義経堂',
        note: '義経の最期の地と伝えられる丘です。北上川と束稲山を見下ろせます。',
      },
      {
        name: '毛越寺',
        note: '庭園が往時の規模を伝えています。政治の中心がここにあったことが分かります。',
      },
    ],
    plays: ['nishikido'],
    people: ['minamoto-yoshitsune', 'fujiwara-hidehira'],
  },
  {
    slug: 'kumano',
    name: '熊野',
    romaji: 'KUMANO',
    reading: 'くまの',
    prefecture: '和歌山県',
    modernName: '田辺市・新宮市・東牟婁郡ほか',
    regionModern: '近畿',
    kind: '社寺',
    enLocation: 'Kumano, Wakayama',
    region: '紀伊',
    lat: 33.84,
    lon: 135.773,
    summary: '三山を結ぶ参詣路が集まる山域です。中世を通じて、身分を越えた人の往来がありました。',
    access: 'JR紀勢本線・紀伊田辺駅または新宮駅から、各社へバスが出ています。',
    plays: [],
    people: [],
  },
  {
    slug: 'setouchi',
    name: '瀬戸内',
    romaji: 'SETOUCHI',
    reading: 'せとうち',
    prefecture: '—',
    modernName: '兵庫・岡山・広島・山口・香川・愛媛の沿岸',
    regionModern: '広域',
    kind: '海・浦',
    enLocation: 'Seto Inland Sea',
    region: '瀬戸内海',
    lat: 34.2,
    lon: 133.4,
    summary: '本州と四国のあいだの内海です。源平の戦いの後半は、ほとんどこの海の上で動きました。',
    plays: ['yashima'],
    people: ['minamoto-yoshitsune'],
  },
]

export const placeBySlug = (slug: string) => PLACES.find((p) => p.slug === slug)
export const placesBySlugs = (slugs: string[]) =>
  slugs.map(placeBySlug).filter((p): p is Place => Boolean(p))

/** 地名に添える「いまのどこか」。地図・年表・本文で同じ文言を使う */
export const modernLocationOf = (slug: string) => {
  const p = placeBySlug(slug)
  if (!p) return undefined
  if (p.prefecture === '—') return p.modernName
  return p.prefecture + p.modernName.replace(p.prefecture, '')
}
