import type { Play } from '@/lib/types'

/** 演目。人物・土地・出典・主題との関係を前提に持つ。 */
export const PLAYS: Play[] = [
  {
    slug: 'hashi-benkei',
    name: '橋弁慶',
    reading: 'はしべんけい',
    romaji: 'HASHI-BENKEI',
    category: '四番目物',
    author: '作者不詳',
    summary:
      '五条の橋で、弁慶と牛若丸が出会う一番です。ただし能では、夜ごと人を斬っているのは十二、三歳の牛若のほうで、弁慶はその噂を聞いて鎮めに橋へ向かいます。',
    hook: '五条の橋で夜ごと人を斬っていたのは、弁慶ではなく十二、三歳の牛若丸でした。噂を聞いて鎮めに出向いた弁慶が、逆に打ち負かされます。',
    form: '現在能',
    shiteType: ['僧・山伏'],
    settingEra: '源平の争乱',
    composedEra: '室町時代',
    people: ['minamoto-yoshitsune', 'benkei'],
    places: ['gojo'],
    sources: ['gikeiki'],
    themes: ['shuju', 'tabi'],
    relatedPlays: ['kurama-tengu', 'eboshi-ori', 'funabenkei'],
  },
  {
    slug: 'funabenkei',
    name: '船弁慶',
    reading: 'ふなべんけい',
    romaji: 'FUNA-BENKEI',
    category: '五番目物',
    author: '観世小次郎信光',
    summary:
      '西国へ落ちる義経の一行が、大物浦から船出します。前半では、都へ帰される静御前が別れの舞を舞います。後半では、海上で嵐に遭った船の前に、壇ノ浦で滅んだ平知盛の怨霊が現れます。',
    hook: '都へ帰される静御前が、義経の前で別れの舞を舞います。そのあと船出した一行を、壇ノ浦で滅ぼされた平知盛の怨霊が、波の上から薙刀を構えて襲います。',
    form: '現在能',
    shiteType: ['女', '霊'],
    settingEra: '源平の争乱',
    composedEra: '室町時代後期',
    people: ['minamoto-yoshitsune', 'benkei', 'shizuka-gozen', 'taira-tomomori'],
    places: ['daimotsu'],
    sources: ['gikeiki', 'heike-monogatari'],
    themes: ['onryo', 'chinkon', 'tabi'],
    relatedPlays: ['hashi-benkei', 'ataka', 'yashima'],
  },
  {
    slug: 'ataka',
    name: '安宅',
    reading: 'あたか',
    romaji: 'ATAKA',
    category: '四番目物',
    author: '作者不詳',
    summary:
      '山伏に姿を変えた義経の一行が、北国の安宅の関で関守の富樫に呼び止められます。弁慶は白紙の巻物を勧進帳と偽って読み上げ、疑われた義経を自分の杖で打って強力だと言い張ります。歌舞伎「勧進帳」の原型にあたる曲です。',
    hook: '山伏に化けた義経一行が、安宅の関で足止めされます。弁慶は白紙の巻物を勧進帳と偽って読み上げ、疑いを逸らすために、主君である義経を杖で打ちます。',
    form: '現在能',
    shiteType: ['僧・山伏'],
    settingEra: '源平の争乱',
    composedEra: '室町時代',
    people: ['minamoto-yoshitsune', 'benkei', 'togashi'],
    places: ['ataka', 'hokurikudo'],
    sources: ['gikeiki'],
    themes: ['shuju', 'tobo', 'hangan-biiki'],
    relatedPlays: ['funabenkei', 'settai', 'hashi-benkei'],
  },
  {
    slug: 'kurama-tengu',
    name: '鞍馬天狗',
    reading: 'くらまてんぐ',
    romaji: 'KURAMA-TENGU',
    category: '五番目物',
    author: '作者不詳',
    summary:
      '鞍馬寺の花見の席で、源氏の子である牛若丸だけが仲間に入れてもらえません。声をかけた山伏が大天狗であることを明かし、牛若に兵法を授けます。英雄譚の出発点に置かれる曲です。',
    hook: '鞍馬寺の花見で、源氏の子である牛若丸だけが仲間に入れてもらえません。ひとり声をかけてきた山伏が正体を明かし、兵法を授けます。',
    form: '現在能',
    shiteType: ['鬼・異類'],
    settingEra: '平安',
    composedEra: '室町時代',
    people: ['minamoto-yoshitsune'],
    places: ['kurama'],
    sources: [],
    themes: ['tabi'],
    relatedPlays: ['hashi-benkei'],
  },
  {
    slug: 'eboshi-ori',
    name: '烏帽子折',
    reading: 'えぼしおり',
    romaji: 'EBOSHI-ORI',
    category: '四番目物',
    author: '作者不詳',
    summary:
      '都を出て奥州へ向かう牛若丸が、道中の烏帽子屋で烏帽子を誂え、名を改めます。その夜、泊まった赤坂の宿を熊坂長範の一党が襲い、牛若がこれを討ち取ります。',
    hook: '都を出た牛若丸が、烏帽子屋で名を改めます。その同じ夜、泊まった宿を襲った盗賊の一党を、この少年がひとりで討ち取ります。',
    form: '現在能',
    shiteType: ['武者'],
    settingEra: '平安',
    composedEra: '室町時代',
    people: ['minamoto-yoshitsune'],
    places: ['omi-kagami'],
    sources: ['gikeiki'],
    themes: ['tabi'],
    relatedPlays: ['kumasaka', 'hashi-benkei'],
  },
  {
    slug: 'kumasaka',
    name: '熊坂',
    reading: 'くまさか',
    romaji: 'KUMASAKA',
    category: '五番目物',
    author: '作者不詳',
    summary:
      '旅の僧の前に現れた僧が、名を明かさないまま弔いを願います。その正体は、牛若丸に討たれた盗賊・熊坂長範の亡霊でした。討たれた側から、あの夜をもう一度語り直す構成です。',
    hook: '旅の僧の前に現れた僧は、牛若丸に討たれた盗賊、熊坂長範の亡霊でした。自分が斬られたその夜を、討たれた側からもう一度やって見せます。',
    form: '夢幻能',
    shiteType: ['霊'],
    settingEra: '平安',
    composedEra: '室町時代',
    people: ['minamoto-yoshitsune'],
    places: ['omi-kagami'],
    sources: [],
    themes: ['haisha', 'onryo'],
    relatedPlays: ['eboshi-ori'],
  },
  {
    slug: 'yashima',
    name: '八島',
    reading: 'やしま',
    romaji: 'YASHIMA',
    category: '二番目物',
    author: '世阿弥',
    summary:
      '屋島の浦で旅の僧が宿を借りた漁師の老人は、義経の亡霊でした。後半では甲冑姿で現れ、修羅道で戦い続ける身のまま、海に落とした弓を拾いに戻った夜を語ります。',
    hook: '屋島で僧が宿を借りた漁師の老人は、義経の亡霊でした。勝ったはずの戦を、修羅道で戦い続ける身のまま語り直します。',
    form: '夢幻能',
    shiteType: ['霊', '武者'],
    settingEra: '源平の争乱',
    composedEra: '室町時代前期',
    people: ['minamoto-yoshitsune'],
    places: ['yashima'],
    sources: ['heike-monogatari'],
    themes: ['haisha', 'chinkon'],
    relatedPlays: ['funabenkei'],
  },
  {
    slug: 'shozon',
    name: '正尊',
    reading: 'しょうぞん',
    romaji: 'SHOZON',
    category: '四番目物',
    author: '作者不詳',
    summary:
      '頼朝の命で義経を討ちに来た土佐坊正尊が、疑いを問われて神仏に誓う起請文を読み上げます。いったんは許されますが、その夜、誓いを破って義経の屋敷を襲います。義経と頼朝の亀裂が、目に見える形で現れる一番です。',
    hook: '頼朝に命じられて義経を討ちに来た土佐坊正尊が、神仏への誓紙を読み上げて疑いを晴らします。そしてその夜、誓いを破って襲いかかります。',
    form: '現在能',
    shiteType: ['武者'],
    settingEra: '源平の争乱',
    composedEra: '室町時代',
    people: ['minamoto-yoshitsune', 'benkei'],
    places: ['kyoto'],
    sources: ['azuma-kagami', 'gikeiki'],
    themes: ['tobo'],
    relatedPlays: ['funabenkei'],
  },
  {
    slug: 'yoshino-shizuka',
    name: '吉野静',
    reading: 'よしのしずか',
    romaji: 'YOSHINO-SHIZUKA',
    category: '三番目物',
    author: '作者不詳',
    summary: '吉野に逃げ込んだ義経を、追手の僧兵たちが捜しています。義経の愛妾である静御前は山に残り、その僧兵たちの前で舞を舞って、義経が落ち延びる時間を稼ぎます。',
    hook: '吉野で義経を追う僧兵たちの前に、愛妾の静御前が進み出て舞いはじめます。義経が山を越える時間を稼ぐための舞です。',
    form: '現在能',
    shiteType: ['女'],
    settingEra: '源平の争乱',
    composedEra: '室町時代',
    people: ['shizuka-gozen', 'minamoto-yoshitsune'],
    places: ['yoshino'],
    sources: ['gikeiki'],
    themes: ['koi', 'tobo'],
    relatedPlays: ['funabenkei'],
  },
  {
    slug: 'settai',
    name: '摂待',
    reading: 'せったい',
    romaji: 'SETTAI',
    category: '四番目物',
    author: '作者不詳',
    summary:
      '信夫の里が舞台です。義経のために死んだ佐藤継信・忠信兄弟の母が、息子たちを弔うため、旅の山伏をもてなしています。その日の客が、当の義経の一行でした。',
    hook: '息子たちを義経のために死なせた老母が、供養のつもりで旅の山伏をもてなします。その客が当の義経一行であることを、母は知りません。',
    form: '現在能',
    shiteType: ['老人'],
    settingEra: '源平の争乱',
    composedEra: '室町時代',
    people: ['minamoto-yoshitsune', 'benkei', 'sato-tadanobu'],
    places: ['shinobu'],
    sources: ['gikeiki'],
    themes: ['chugi', 'chinkon', 'haisha'],
    relatedPlays: ['ataka', 'hashi-benkei', 'funabenkei'],
  },
  {
    slug: 'nishikido',
    name: '錦戸',
    reading: 'にしきど',
    romaji: 'NISHIKIDO',
    category: '四番目物',
    author: '作者不詳',
    summary:
      '義経が死んだあとの平泉が舞台です。藤原秀衡の遺言を守ろうとした末子の泉三郎を、兄の藤原泰衡と錦戸太郎が謀って討ちます。義経の物語の外側で起きたことを扱う、救いのない曲です。',
    hook: '義経が死んだあとの平泉の話です。父の遺言を守ろうとした弟を、兄たちが謀って討ちます。',
    form: '現在能',
    shiteType: ['武者'],
    settingEra: '鎌倉',
    composedEra: '室町時代',
    people: ['fujiwara-hidehira'],
    places: ['hiraizumi'],
    sources: ['azuma-kagami'],
    themes: ['haisha'],
    relatedPlays: ['settai'],
  },
  {
    slug: 'atsumori',
    name: '敦盛',
    reading: 'あつもり',
    romaji: 'ATSUMORI',
    category: '二番目物',
    author: '世阿弥',
    summary:
      '一ノ谷で十六歳の平敦盛を討った熊谷直実が、出家して蓮生と名を変え、供養のために戦場へ戻ります。そこへ、討たれた敦盛の亡霊が現れます。',
    hook: '一ノ谷で十六歳の平敦盛を討った熊谷直実が、出家して供養に戻ってきます。そこへ、討たれた当の敦盛が亡霊となって現れます。',
    form: '夢幻能',
    shiteType: ['霊', '武者'],
    settingEra: '源平の争乱',
    composedEra: '室町時代前期',
    people: ['taira-atsumori'],
    places: ['ichinotani'],
    sources: ['heike-monogatari'],
    themes: ['haisha', 'chinkon'],
    relatedPlays: ['yashima'],
  },
  {
    slug: 'izutsu',
    name: '井筒',
    reading: 'いづつ',
    romaji: 'IZUTSU',
    category: '三番目物',
    author: '世阿弥',
    summary:
      '在原寺の井筒のほとりが舞台です。里の女として現れた在原業平の妻の亡霊が、幼なじみだった二人の約束を語り、夫の形見の装束と冠を身につけて井筒を覗き込みます。',
    hook: '在原業平の妻の亡霊が、夫の形見の装束と冠を身につけて井戸を覗き込みます。水に映った自分の姿のなかに、亡き夫の面影を見ます。',
    form: '夢幻能',
    shiteType: ['女', '霊'],
    settingEra: '平安',
    composedEra: '室町時代前期',
    people: ['ariwara-narihira'],
    places: [],
    sources: ['ise-monogatari'],
    themes: ['koi'],
    relatedPlays: [],
  },
  {
    slug: 'hagoromo',
    name: '羽衣',
    reading: 'はごろも',
    romaji: 'HAGOROMO',
    category: '三番目物',
    author: '作者不詳',
    summary: '三保の松原で、漁師の白龍が松にかかった羽衣を拾います。天へ帰れなくなった天人がそれを返してほしいと請い、漁師は舞を見せることを条件に返します。',
    hook: '三保の松原で漁師が拾った羽衣は、天人のものでした。返してほしいと請われた漁師が、舞を見せてくれるなら、と条件を出します。',
    form: '現在能',
    shiteType: ['神・天人'],
    settingEra: '時代を定めない',
    composedEra: '室町時代',
    people: [],
    places: [],
    sources: [],
    themes: [],
    relatedPlays: [],
  },
  {
    slug: 'shunkan',
    name: '俊寛',
    reading: 'しゅんかん',
    romaji: 'SHUNKAN',
    category: '四番目物',
    author: '作者不詳',
    summary:
      '鬼界ヶ島が舞台です。流された三人のもとへ赦免の船が着きますが、読み上げられた赦免状に俊寛の名前だけがありません。残される者を正面から描きます。',
    hook: '鬼界ヶ島に流された三人のもとへ、赦免の船が来ます。読み上げられた名の中に、俊寛のものだけがありません。',
    form: '現在能',
    shiteType: ['僧・山伏'],
    settingEra: '源平の争乱',
    composedEra: '室町時代',
    people: [],
    places: [],
    sources: ['heike-monogatari'],
    themes: ['haisha'],
    relatedPlays: [],
  },
]

export const playBySlug = (slug: string) => PLAYS.find((p) => p.slug === slug)
export const playsBySlugs = (slugs: string[]) =>
  slugs.map(playBySlug).filter((p): p is Play => Boolean(p))
